function [fitresult, gof] = createFit(Time, MFPT)
%CREATEFIT(TIME,MFPT)
%  Create a fit.
%
%  Data for 'Time vs Chased' fit:
%      X Input : Time
%      Y Output: MFPT
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 17-May-2020 16:59:46


%% Fit: 'Time vs Chased'.
[xData, yData] = prepareCurveData( Time, MFPT );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [43.1949628886972 -2.43444366261487 34.2052984488567 0.0111503396124966];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Time vs Chased' );
% h = plot( fitresult, xData, yData );
h1 = plot(fitresult,'b');
hold on
h2 = scatter(xData,yData,32,'k','filled');

legend( [h1 h2], {'Fitted Curve', 'Simulation Data'}, 'Location', 'NorthEast' );
% Label axes
set(gca,'XLim',[0,10.2])
set(gca,'YLim',[30,60])
xlabel('Reorientation Period T (s)','FontSize',16)
ylabel('Percentage Captured','FontSize',16)
title('Escaping Searches with Periodic Reorientaion','FontSize',20)
% set(gca,'xticklabel',{0,1,2,3,4,5,6,7,8,9,10},'FontSize',16)
set(gca,'yticklabel',{30,35,40,45,50,55,60},'FontSize',16)
grid on
axis('square')


