function [fitresult, gof] = Chased_vs_T_MFPT(x, MFPT1)
%CREATEFIT(X,MFPT1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: MFPT1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-Jul-2020 16:18:02


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, MFPT1 );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [249.373740756926 -1.02406242871976 54.8787112529564 0.00712918483098244];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Time vs MFPT' );
h1 = plot(fitresult,'b');
hold on
h2 = scatter(xData,yData,32,'k','filled');

legend( [h1 h2], {'Fitted MFPT vs. T', 'MFPT vs. T'}, 'Location', 'NorthEast' );
% Label axes
set(gca,'XLim',[0,10.2])
% set(gca,'YLim',[0,100])
xlabel('Reorientation Period','FontSize',18)
ylabel('Mean First Passage Time (s)','FontSize',18)
title('Fitted Curve of MFPT and Reorientation Period','FontSize',20)
set(gca,'xticklabel',{0,1,2,3,4,5,6,7,8,9,10},'FontSize',18)
% set(gca,'yticklabel',{0,20,40,60,80,100},'FontSize',18)
grid on


