function [fitresult, gof] = createFits(x, MFPT1, E, MFPT2)
%CREATEFITS(X,MFPT1,E,MFPT2)
%  Create fits.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: MFPT1
%  Data for 'untitled fit 2' fit:
%      X Input : E
%      Y Output: MFPT2
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-Jul-2020 16:24:22

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 2, 1 );
gof = struct( 'sse', cell( 2, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, MFPT1 );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [249.373740756926 -1.02406242871976 54.8787112529564 0.00712918483098244];

% Fit model to data.
[fitresult{1}, gof(1)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Time vs Chased' );
% h = plot( fitresult, xData, yData );
h1 = plot(fitresult{1},'b');
hold on
h2 = scatter(xData,yData,32,'k','filled');

legend( [h1 h2], {'Chased Percentage vs. Error Threshold', 'Chased Percentage vs. Error Threshold'}, 'Location', 'NorthEast' );
% Label axes
set(gca,'XLim',[0,3.2])
% set(gca,'YLim',[0,100])
xlabel('Error Threshold','FontSize',18)
ylabel('Mean First Passage Time (s)','FontSize',18)
title('Fitted Curve of Chased Percentage and Error Threshold','FontSize',20)
set(gca,'xticklabel',{0,1,2,3,4,5,6,7,8,9,10},'FontSize',18)
% set(gca,'yticklabel',{0,20,40,60,80,100},'FontSize',18)
grid on


