function [fitresult, gof] = createFit(N, B100V5)
%CREATEFIT(N,B100V5)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : N
%      Y Output: B100V5
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 17-May-2020 16:44:58


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( N, B100V5 );

% Set up fittype and options.
ft = fittype( 'rat11' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.171186687811562 0.706046088019609 0.0318328463774207];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
h1 = plot(fitresult,'b');
hold on
h2 = scatter(xData,yData,32,'k','filled');

legend( [h1 h2], {'Fitted Curve', 'Simulation Data'}, 'Location', 'SouthEast','FontSize',16 );
% Label axes
set(gca,'Xlim',[0,16])
set(gca,'YLim',[0,100])
xlabel('Number of Searchers','FontSize',16)
ylabel('Percentage Captured','FontSize',16)
% title('Fitted Curve of Chased Percentage and Number of Chasers (B100V5)','FontSize',20)
title('Results for Multiple Searchers','FontSize',20)
set(gca,'xticklabel',{0,2,4,6,8,10,12,14,16},'FontSize',16)
% set(gca,'ytick',{0,20,40,60,80,100})
% set(gca,'yticklabel',{0,20,40,60,80,100},'FontSize',16)
grid on


