function [fitresult, gof] = Sigma_vs_T(sigma, T)
%CREATEFIT(SIGMA,T)
%  Create a fit.
%
%  Data for 'Fit of Sigma and T' fit:
%      X Input : sigma
%      Y Output: T
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 12-May-2019 00:47:56


%% Fit: 'Fit of Sigma and T'.
[xData, yData] = prepareCurveData( sigma, T );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [32.6180902494528 -1.86975762332451];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Fit of Sigma and T' );
plot( fitresult,'b');
hold on
scatter(sigma,T,48,'k','o');
legend( 'Fit of \sigma_d and T^*','T^* vs \sigma_d', 'Location', 'NorthEast','FontSize',18);
% Label axes
xlim([0.4 1.6])
xlabel('Drifting Tendency \sigma_d','FontSize',18)
ylabel('Optimal Reorientation Period T^* (s)','FontSize',18)
ax = gca;
ax.FontSize = 18;
grid on


