function [fitresult, gof] = Time_vs_Sigma(Period, MFPT1)
%CREATEFIT(PERIOD,MFPT1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : Period
%      Y Output: MFPT1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 10-Jul-2020 10:45:16


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( Period, MFPT1 );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [468.95592361866 -1.08734161958569 74.2292092150647 0.0106967067779324];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Period vs MFPT' );
% h = plot( fitresult, xData, yData );
h1 = plot(fitresult,'b');
hold on
h2 = scatter(xData,yData,32,'k','filled');

legend( [h1 h2], {'MFPT vs. Reorientation Period', 'Fitted MFPT vs. Reorientation Period'}, 'Location', 'NorthEast' );
% Label axes
set(gca,'XLim',[0,10.2])
% set(gca,'YLim',[25,75])
xlabel('Reorientation Period','FontSize',18)
ylabel('MFPT (s)','FontSize',18)
title('Fitted Curve of MFPT and Reorientation Period','FontSize',20)
set(gca,'xticklabel',{0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0},'FontSize',18)
% set(gca,'yticklabel',{25,30,35,40,45,50,55,60,65,70,75},'FontSize',18)
grid on